name: KitPvP
version: ${project.version}
main: nl.alvinvrolijk.kitpvp.KitPvP
api-version: 1.13
authors: [AlvinDDG]
description: A simple KitPvP plugin
commands:
  createarena:
    description: Create a new arena
  createkit:
    description: Create kit
  removearena:
    description: Remove a arena
  removekit:
    description: Remove a kit
  kitlist:
    description: List of Kits
  arenalist:
    description: List of Arena's
  updatekit:
    description: Update a kit
  getkit:
    description: Get a kit
  setspawn:
    description: Set spawn location
  spawn:
    description: Teleport to spawn
permissions:
  kitpvp.command.createarena:
    default: op
  kitpvp.command.createkit:
    default: op
  kitpvp.command.removearena:
    default: op
  kitpvp.command.removekit:
    default: op
  kitpvp.command.kitlist:
    default: op
  kitpvp.command.arenalist:
    default: op
  kitpvp.command.updatekit:
    default: op
  kitpvp.command.getkit:
    default: op
  kitpvp.command.setspawn:
    default: op
  kitpvp.command.spawn:
    default: true